version: '3.9'

services:

  main:
    image: main
    build:
      context: "./main"
    container_name: main
    volumes:
      - staticfiles:/home/main/static
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    env_file:
      - ./envs/.env.main-prod
    environment:
      - ENVIRONMENT=PROD
      - DJANGO_SUPERUSER_PASSWORD=root
      - DJANGO_SUPERUSER_USERNAME=root
    depends_on:
      - db
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 500M
    networks:
      - db
      - nginx

  front-end:
    image: front-end
    build:
      context: "./front"
    container_name: front-end
    ports:
      - 80:80
    restart: always
    env_file:
      - ./envs/.env.front-prod
    environment:
      - ENVIRONMENT=PROD
    depends_on:
      - main
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 250M
    networks:
      - nginx

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    volumes:
      - type: volume
        source: staticfiles
        target: /home/static
      - type: bind
        source: ./nginx
        target: /etc/nginx/conf.d
        read_only: true
    depends_on:
      - main
    ports:
      - target: 81
        published: 81
        protocol: tcp
        mode: ingress
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 250M
    networks:
      - nginx

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: ingress
    env_file:
      - ./envs/.env.db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 500M
    networks:
      - db

  # pgadmin:
  #   image: dpage/pgadmin4:7.2
  #   container_name: pgadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - 5050:5050
  #   env_file:
  #     - ./envs/.env.db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: root
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   restart: unless-stopped
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.10'
  #         memory: 200M
  #   networks:
  #     - db

volumes:
  pgdata:
  pgadmin-data:
  staticfiles:

networks:
  db:
    driver: bridge
  nginx:
    driver: bridge
