version: '3.9'

services:

  main:
    image: main
    build: "./main"
    container_name: main
    ports:
      - 8000:8000
    env_file: ./envs/.env.main-dev
    restart: always
    depends_on:
      db:
        condition: service_healthy

  front:
    image: front
    build:
      context: "./front"
      target: public
    container_name: front
    ports:
      - 80:80
    env_file: ./envs/.env.front-dev
    restart: always
    depends_on:
     - nginx

  db:
    image: postgres:16
    container_name: db
    ports:
      - 5432:5432
    env_file: ./envs/.env.db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db -U root" ]
