version: '3.9'

services:

  main:
    image: main
    build:
      context: "./main"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: main
    volumes:
      - ./main:/home/main
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./envs/.env.main-dev
    environment:
      - ENVIRONMENT=DEV
      - DJANGO_SUPERUSER_PASSWORD=root
      - DJANGO_SUPERUSER_USERNAME=root
    depends_on:
      - db

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./envs/.env.db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

  front-end:
    image: front-end
    build: ./front
    container_name: front-end
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - main